version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "angularjs",
    "meteor",
    "ember",
    "vue"
  ]
  environment = [
    "nodejs",
    "jquery",
    "browser",
    "mongo",
    "jest",
    "cypress",
    "mocha",
    "vitest",
    "jasmine"
  ]

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "isort"

[[transformers]]
name = "ruff"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "black"

[[transformers]]
name = "yapf"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "dotnet-format"