version = 1

[[analyzers]]
name = "solhint"
type = "community"

[[analyzers]]
name = "slither"
type = "community"

[[analyzers]]
name = "kube-linter"
type = "community"

[[analyzers]]
name = "dart-analyze"
type = "community"

[[analyzers]]
name = "cfn-lint"
type = "community"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "angularjs",
    "meteor",
    "ember",
    "vue"
  ]
  environment = [
    "nodejs",
    "jquery",
    "browser",
    "mongo",
    "jest",
    "cypress",
    "mocha",
    "vitest",
    "jasmine"
  ]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/mikhaeelatefrizk/flashcardsproject"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "isort"

[[transformers]]
name = "ruff"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "black"

[[transformers]]
name = "yapf"

[[transformers]]
name = "swift-format"

[[transformers]]
name = "scalafmt"

[[transformers]]
name = "standardrb"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "dotnet-format"
